language: python
python: "2.7"
sudo: false
branches:
     only:
          - master
before_script: ./build/scripts/setup_credentials.sh
script: ./build/scripts/deploy.sh
before_install:
  - chmod +x ./build/scripts/setup_credentials.sh
  - chmod +x ./build/scripts/deploy.sh